mysite/urls.py
from django.urls import include, path
from django.contrib import admin

urlpatterns = [
    path('', include('polls.urls')),
    path('admin/', admin.site.urls),
    path('auth/', include('authentication.urls'))
]

polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:question_id>/', views.detail, name='detail'),
    path('<int:question_id>/results/', views.results, name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
    path('create/', views.create_question, name='create'),
    path('<int:question_id>/update/', views.update_question, name='update_question'),
    path('<int:question_id>/delete/', views.delete_question, name='delete_question'),
    path('<int:question_id>/create_choices/', views.create_choice, name='create_choice'),
    path('<int:question_id>/delete_choice/<int:choice_id>/', views.delete_choice, name='delete_choice'),
]

polls/models.py
import datetime

from django.db import models
from django.utils import timezone
from django.contrib import admin

from django.contrib.auth import get_user_model

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField("date published", default = timezone.now)
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, default=0)

    def __str__(self):
        return self.question_text
    
    @admin.display(
        boolean=True,
        ordering="pub_date",
        description="Published recently?",
    )
    
    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

polls/forms.py
from django import forms
from django.forms import inlineformset_factory

from .models import Question
from .models import Choice


class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ['question_text']


class ChoiceForm(forms.ModelForm):
    class Meta:
        model = Choice
        fields = ['choice_text']


ChoiceFormSet = inlineformset_factory(
    Question,
    Choice,
    form=ChoiceForm,
    extra=4,
    can_delete=True
)

polls/views.py
from django.contrib import messages
from django.db.models import F
from django.forms import inlineformset_factory
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse
from django.contrib.auth.decorators import login_required


from .models import Choice, Question
from .forms import QuestionForm, ChoiceFormSet





def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')
    context = {'latest_question_list': latest_question_list}
    return render(request, 'polls/index.html', context)


def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    user = question.user
    context = {
        'question': question,
        'user': user,
    }
    return render(request, 'polls/detail.html', context)


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(
            request,
            'polls/detail.html',
            {
                'question': question,
                'error_message': "You didn't select a choice.",
            },
        )
    else:
        selected_choice.votes = F('votes') + 1
        selected_choice.save()
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))


def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/results.html', {'question': question})

@login_required
def create_question(request):
    if request.method == 'POST':
        form = QuestionForm(request.POST)
        formset = ChoiceFormSet(request.POST, instance=Question())
        if form.is_valid() and formset.is_valid():
            question = form.save(commit=False)
            question.user_id = request.user.id
            question.save()
            choices = formset.save(commit=False)
            for choice in choices:
                choice.question = question
                choice.save()
            return redirect('polls:detail', question_id=question.id)
    else:
        form = QuestionForm()
        formset = ChoiceFormSet(instance=Question())
    return render(request, 'polls/create_question.html', {'form': form, 'formset': formset})


@login_required
def update_question(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    ChoiceFormSet = inlineformset_factory(Question, Choice, fields=('choice_text',), can_delete=True, extra=0)
    if request.user.id != question.user_id:
        messages.error(request, "You do not have permission to update this question.")
        return redirect('polls:detail', question_id=question.id)
    if request.method == 'POST':
        form = QuestionForm(request.POST, instance=question)
        formset = ChoiceFormSet(request.POST, instance=question)
        if form.is_valid() and formset.is_valid():
            form.save()
            choices = formset.save(commit=False)
            for choice in choices:
                choice.question = question
                choice.save()
            return redirect('polls:detail', question_id=question.id)
    else:
        form = QuestionForm(instance=question)
        formset = ChoiceFormSet(instance=question)
    return render(request, 'polls/update_question.html', {'form': form, 'formset': formset, 'question': question})


@login_required
def delete_question(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    if request.user.id != question.user_id:
        messages.error(request, "You do not have permission to delete this question.")
        return redirect('polls:detail', question_id=question.id)
    if request.method == 'POST':
        question.delete()
        return redirect('polls:index')
    return render(request, 'polls/delete_question.html', {'question': question})


@login_required
def create_choice(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    if request.method == 'POST':
        formset = ChoiceFormSet(request.POST, instance=question)
        if formset.is_valid():
            formset.save()
            return redirect('polls:update_question', question_id=question.id)
    else:
        formset = ChoiceFormSet(instance=question, queryset=Choice.objects.none())
    return render(request, 'polls/create_choices.html', {'formset': formset, 'question': question})


@login_required
def delete_choice(request, question_id, choice_id):
    question = get_object_or_404(Question, pk=question_id)
    choice = get_object_or_404(Choice, pk=choice_id)
    if request.method == 'POST':
        choice.delete()
        return redirect('polls:update_question', question_id=question.id)
    return render(request, 'polls/delete_choice.html', {'question': question, 'choice': choice})

templates/polls/create_choices.html
{% extends 'base.html' %}
<!--  -->
{% block title %}Creation choices{% endblock %}
<!--  -->
{% block content %}

<h1>Add Choices for {{ question.question_text }}</h1>
<form method="post">
  {% csrf_token %}
  <!--  -->
  {{ formset.management_form }}
  <!--  -->
  {% for form in formset.forms %}
  <div>
    {% for hidden in form.hidden_fields %}
    <!--  -->
    {{ hidden }}
    <!--  -->
    {% endfor %}
    <!--  -->
    {{ form.choice_text.label }}
    <!--  -->
    {{ form.choice_text }}
  </div>
  {% endfor %}
  <button type="submit">Save Choices</button>
</form>

{% endblock %}

templates/polls/create_question.html
{% extends 'base.html' %}
<!--  -->
{% block title %}Creation poll{% endblock %}
<!--  -->
{% block content %}

<h1>Create Question</h1>
<form method="post" class="create-question">
	{% csrf_token %}
	<!--  -->
	{{ form.as_p }}
	<!--  -->
	{{ formset.management_form }}
	<!--  -->
	{% for choice_form in formset %}
	<div>{{ choice_form.choice_text.label }} {{ choice_form.choice_text }}</div>
	{% endfor %}
	<button type="submit">Create</button>
</form>

{% endblock %}

templates/polls/delete_choice.html
{% extends 'base.html' %}
<!--  -->
{% block title %}Confirm delete{% endblock %}
<!--  -->
{% block content %}

<h1>Delete Choice</h1>
<p>Are you sure you want to delete the choice: "{{ choice.choice_text }}"?</p>
<form method="post">
  {% csrf_token %}
  <button type="submit">Delete</button>
</form>

{% endblock %}

templates/polls/delete_question.html
{% extends 'base.html' %}
<!--  -->
{% block title %}Confirm delete {{ question_text }}{% endblock %}
<!--  -->
{% block content %}

<h1>Are you sure you want to delete "{{ question.question_text }}"?</h1>
<form method="post">
  {% csrf_token %}
  <button type="submit">Yes, delete</button>
</form>

{% endblock %}

templates/polls/detail.html
{% extends 'base.html' %}
<!--  -->
{% block title %} {{ question.question_text }} {% endblock %}
<!--  -->
{% block content %}

<form action="{% url 'polls:vote' question.id %}" method="post">
  {% csrf_token %}
  <fieldset>
    <legend><h1>{{ question.question_text }}</h1></legend>
    {% if error_message %}
    <p><strong>{{ error_message }}</strong></p>
    {% endif %}
    <!--  -->
    {% for choice in question.choice_set.all %}
    <input
      type="radio"
      name="choice"
      id="choice{{ forloop.counter }}"
      value="{{ choice.id }}"
    />
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label
    ><br />
    {% endfor %}
  </fieldset>
  <input type="submit" value="Vote" />
</form>
<div class="control-panel">
  <a
    class="btn-control-question"
    href="{% url 'polls:update_question' question.id %}"
  >
    Update Question
  </a>
  <a
    class="btn-control-question"
    href="{% url 'polls:delete_question' question.id %}"
  >
    Delete Question
  </a>
  <a class="btn-control-question" href="{% url 'polls:results' question.id %}">
    View Results
  </a>
</div>
<div>
  <p>Poll created by {{ user.username }}</p>
</div>

{% endblock %}

templates/polls/index.html
{% extends 'base.html' %}
<!--  -->
{% block content %}
<!--  -->
{% if latest_question_list %}
<ul class="listOfQuestions">
	{% for question in latest_question_list %}
	<li>
		<a href="{% url 'polls:detail' question.id %}">
			{{ question.question_text }}
		</a>
	</li>
	{% endfor %}
</ul>
{% else %}
<p>No polls are available.</p>
{% endif %}

<form method="get" action="{% url 'polls:create' %}">
	<input type="submit" value="Create new question" />
</form>

{% endblock %}

templates/polls/results.html
{% extends 'base.html' %}
<!--  -->
{% block title %} {{ question.question_text }} {% endblock %}
<!--  -->
{% block content %}
<h1>{{ question.question_text }}</h1>

<ul>
  {% for choice in question.choice_set.all %}
  <li>{{ choice.choice_text }} -- {{ choice.votes }}</li>
  {% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>
{% endblock %}

templates/polls/update_question.html
{% extends 'base.html' %}
<!--  -->
{% block title %} Updating {{ question.question_text }} {% endblock %}
<!--  -->
{% block content %}
<!--  -->

<h1>Update Question</h1>
<form method="post">
  {% csrf_token %}
  <!--  -->
  {{ form.as_p }}
  <!--  -->
  {{ formset.management_form }}
  <!--  -->
  {% for choice_form in formset %}
  <div>
    {% for hidden in choice_form.hidden_fields %}
    <!--  -->
    {{ hidden }}
    <!--  -->
    {% endfor %}
    <!--  -->
    {{ choice_form.choice_text.label }}
    <!--  -->
    {{ choice_form.choice_text }}
    <!--  -->
    {% if choice_form.instance.pk %}
    <a
      href="{% url 'polls:delete_choice' question.id choice_form.instance.pk %}"
    >
      Delete
    </a>
    {% endif %}
  </div>
  {% endfor %}
  <div>
    <a href="{% url 'polls:create_choice' question.id %}">Add Choices</a>
  </div>
  <button type="submit">Update</button>
</form>
{% endblock %}