authentication/urls.py
from django.urls import path
from . import views

app_name = 'auth'
urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('signup/', views.register_view, name='signup'),
    path('logout/', views.logout_view, name='logout'),
]

mysite/urls.py
from django.urls import include, path
from django.contrib import admin

urlpatterns = [
    path('', include('polls.urls')),
    path('admin/', admin.site.urls),
    path('auth/', include('authentication.urls'))
]

polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:question_id>/', views.detail, name='detail'),
    path('<int:question_id>/results/', views.results, name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
    path('create/', views.create_question, name='create'),
    path('<int:question_id>/update/', views.update_question, name='update_question'),
    path('<int:question_id>/delete/', views.delete_question, name='delete_question'),
    path('<int:question_id>/create_choices/', views.create_choice, name='create_choice'),
    path('<int:question_id>/delete_choice/<int:choice_id>/', views.delete_choice, name='delete_choice'),
]

templates/base.html
<!DOCTYPE html>
<html>
	<head>
		<title>{% block title %}Polls{% endblock %}</title>
	</head>
	<body>
		<!--  -->
		{% block header %}

		<header>
			<nav>
				<li>
					<a href="{% url 'polls:index' %}" class="btn-home">Home</a>
				</li>
				<li>
					{% if user.is_authenticated %}
					<form id="logout-form" method="post" action="{% url 'auth:logout' %}">
						{% csrf_token %}
						<label>
							Logged in as {{ user.username }}
							<button type="submit" class="btn btn-link">Logout</button>
						</label>
						{% else %}
						<button class="auth-btn btn-login">
							<a href="{% url 'auth:login' %}">Login</a>
						</button>
						<button class="auth-btn btn-signup">
							<a href="{% url 'auth:signup' %}">Signup</a>
						</button>
						{% endif %}
					</form>
				</li>
			</nav>
		</header>
		{% endblock %}

		<main>
			{% block content %} {% endblock %}
			<!--  -->
			{% if messages %}
			<!--  -->
			{% for message in messages %}
			<!--  -->
			<p class="error-message">{{ message }}</p>
			<!--  -->
			{% endfor %}
			<!--  -->
			{% endif %}
		</main>
	</body>
</html>

templates/base_authentication.html
{% extends 'base.html' %}
<!--  -->
{% block content %}
<!--  -->
{% endblock %}